### ISSUE TITLE
Recrutement Assistant (C'est wtfreacher) 

### ISSUE THREAD

**Issue by HerZay** [Raph9213/ExtraServ#3]
Bonjour je m'appelle Mathias IRL 
J'ai déjà été modérateur sur des petits serveur qui ont fermés 
J'ai 12ans et demi
Je joue a minecraft depuis 4ans bientôt 
J'ai 16.5 de moyenne globale 
Je n'ai pas d'horaire pendant les vacances
Et je ne sais pas mes horaires vu que je n'ai pas eu mon emploi du temps mais je vous le dirais des que je l'aurais 
Je suis a l'écoute et je suis très bon en orthographe et en anglais 
J'ai été peu codeur il y a 1 an et j'avais une chaîne youtube 
Je connais déjà des membres du staff comme L1Konnu, Azoy_TV, et Emma et Swog (qui n'est plus assistant et qui s'est fait bannir ) .

                                                                                                           Cordialement, HerZay alias Mathias

**Comment by HamidV7** [comment]
Donc, à mon avis ta essayer de tout résumer sur une seul candidature mais y'a beaucoup de chose qui manque, ta pas raconter comment ta connu le serveur et autre choses dans le modèle d'une candidature.
 
 J'vais te donner mon avis finale, candidature assez petite + beaucoups de fautes d'orthographes, ainsi que 12 ans n'est pas l'âge idéal pour passer en tant qu'assistant sur nos plateformes... moi je te propose 
une dernière chance, c'est de refaire une candidature bien expliqué avec t'es motivations et une bonne présentation IRL et IG, et surtout sans fautes d'orthographes, voilà c'étais tout :+1: 

      **ExtraLand - 1.8>1.13**

**Comment by Raph9213** [comment]
Réponse indiquer je lock.
